name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
      
    - uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
    - name: Build the Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64/v8
        push: true
        tags: |
          ${{secrets.DOCKER_USERNAME}}/regression:${{ steps.vars.outputs.tag }}
